# Generated by Django 3.1.4 on 2021-02-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_urgent',
            field=models.BooleanField(blank=True),
        ),
    ]
